"""
sample_pipeline
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
import pandas as pd
import pendulum


@aql.dataframe(task_id="hello_world")
def hello_world_func():
    return "Hello"

default_args={
    "owner": "yashdeepsant@eaton.com,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="*/10 * * * *",
    start_date=pendulum.from_format("2023-09-04", "YYYY-MM-DD").in_tz("Asia/Kolkata"),
    catchup=True,
    owner_links={
        "yashdeepsant@eaton.com": "mailto:yashdeepsant@eaton.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/cllyrswtd00k001mvcn1z9xau/cloud-ide/clm4my5j800ii01kj3km92c30/clm4myjxq00iq01kv2nitm2jt",
    },
)
def sample_pipeline():
    hello_world = hello_world_func()

dag_obj = sample_pipeline()
